# applies to podtato-head-entry deployment only
ingress:
  className: nginx
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: kubrix-ehwuascht-qa.demo-prime.kubrix.cloud
    dns.gardener.cloud/ttl: "180"
  hosts:
    - host: kubrix-ehwuascht-qa.demo-prime.kubrix.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
